steps:
  - id: Build and Push
    name: gcr.io/kaniko-project/executor:latest
    args:
      - --context=.
      - --dockerfile=Dockerfile
      - --destination=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - --destination=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:latest
      - --cache=true
    env:
      - "DOCKER_CONFIG=/kaniko/.docker"
    waitFor: ["-"]

  - id: Substitute kustomization
    name: "debian:stable-slim"
    entrypoint: "bash"
    args:
      - -c
      - |
        apt-get update > /dev/null && apt-get install -y gettext-base --no-install-recommends > /dev/null || true
        envsubst < k8s/kustomization.yaml > k8s/kustomization.processed.yaml
        mv k8s/kustomization.processed.yaml k8s/kustomization.yaml
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'REPO_NAME=$REPO_NAME'
      - '_SERVICE_NAME=$_SERVICE_NAME'
    waitFor: ["-"]

  - id: Migrate
    name: $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    entrypoint: npx
    args: ["prisma", "migrate", "deploy"]
    secretEnv:
      - DATABASE_URL
    waitFor: ["Build and Push"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - "--platform=managed"
      - >-
        --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - "--region=$_DEPLOY_REGION"
      - "--quiet"
    id: Deploy Cloud Run
    entrypoint: gcloud
    waitFor: ["Migrate"]

  - name: "gcr.io/cloud-builders/kubectl"
    env:
      - "CLOUDSDK_COMPUTE_REGION=$_DEPLOY_REGION"
      - "CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER"
      - "PROJECT_ID=$PROJECT_ID"
    args:
      - apply
      - "-k"
      - k8s
    id: Deploy GKE
    waitFor: ["Substitute kustomization", "Migrate"]

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _DEPLOY_REGION: us-east1
  _AR_HOSTNAME: us-east1-docker.pkg.dev
  _PLATFORM: managed
  _SERVICE_NAME: abroad-api
  _TRIGGER_ID: ""
  _GKE_CLUSTER: ""

tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - abroad-api

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
      env: DATABASE_URL
