// src/types.ts
const typeKeys = [
  'AppConfig',
  'DeadLetterController',
  'ExchangeBalanceUpdatedController',
  'CeloPaymentVerifier',
  'CeloWalletHandler',
  'FlowExecutorRegistry',
  'FlowOrchestrator',
  'FlowStepExecutor',
  'IDatabaseClientProvider',
  'IDepositVerifier',
  'IDepositVerifierRegistry',
  'IExchangeProvider',
  'IExchangeProviderFactory',
  'ICorridorPricingProvider',
  'IKycService',
  'IKycDocumentStorage',
  'ILockManager',
  'IOutboxDispatcher',
  'ILogger',
  'IPartnerService',
  'IOpsAuthService',
  'IPaymentService',
  'IPaymentServiceFactory',
  'IPayoutStatusAdapter',
  'IPixQrDecoder',
  'IQueueHandler',
  'ISecretManager',
  'ISlackNotifier',
  'ITreasuryBalanceSource',
  'IWalletHandlerFactory',
  'IWebhookNotifier',
  'IWebSocketService',
  'OutboxWorker',
  'PaymentStatusUpdatedController',
  'PaymentUseCase',
  'QuoteUseCase',
  'ReceivedCryptoTransactionController',
  'ReceivedCryptoTransactionUseCase',
  'SolanaPaymentVerifier',
  'SolanaWalletHandler',
  'StellarWalletHandler',
  'StellarOrphanRefundService',
  'StellarListener',
  'TransactionAcceptanceService',
  'TransactionStatusService',
] as const

type TypeKey = typeof typeKeys[number]

export const TYPES: Record<TypeKey, symbol> = Object.freeze(
  Object.fromEntries(typeKeys.map(key => [key, Symbol.for(key)])) as Record<TypeKey, symbol>,
)
