apiVersion: apps/v1
kind: Deployment
metadata:
  name: abroad-stellar
  labels:
    app: abroad-stellar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abroad-stellar
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: abroad-stellar
    spec:
      containers:
        - name: abroad-stellar-container
          image: abroad-stellar-container:latest
          command: ["node"]
          args: ["dist/stellar/index.js"]
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "pgrep abroad-stellar-container || exit 1"
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "pgrep abroad-stellar-container || exit 1"
            initialDelaySeconds: 10
            periodSeconds: 15
