apiVersion: apps/v1
kind: Deployment
metadata:
  name: abroad-listeners
  labels:
    app: abroad-listeners
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abroad-listeners
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: abroad-listeners
    spec:
      serviceAccountName: abroad-listeners-sa
      containers:
        - name: abroad-listeners-container
          image: abroad-listeners-container:latest
          command: ["node"]
          args: ["dist/listeners.js"]
          imagePullPolicy: Always
          env:
            - name: HEALTH_PORT
              value: "3000"
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
