apiVersion: apps/v1
kind: Deployment
metadata:
  name: abroad-consumers
  labels:
    app: abroad-consumers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abroad-consumers
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: abroad-consumers
    spec:
      serviceAccountName: abroad-stellar-sa
      containers:
        - name: abroad-consumers-container
          image: abroad-consumers-container:latest
          command: ["node"]
          args: ["dist/consumers.js"]
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - ps aux | grep '[n]ode dist/consumers.js'
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: abroad-consumers-sa