apiVersion: apps/v1
kind: Deployment
metadata:
  name: abroad-listeners
  labels:
    app: abroad-listeners
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abroad-listeners
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: abroad-listeners
    spec:
      serviceAccountName: abroad-stellar-sa
      containers:
        - name: abroad-listeners-container
          image: abroad-listeners-container:latest
          command: ["node"]
          args: ["dist/listeners.js"]
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - ps aux | grep '[n]ode dist/listeners.js'
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3


---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: abroad-listeners-sa
