apiVersion: apps/v1
kind: Deployment
metadata:
  name: abroad-stellar
  labels:
    app: abroad-stellar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abroad-stellar
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: abroad-stellar
    spec:
      serviceAccountName: abroad-stellar-sa
      containers:
        - name: abroad-stellar-container
          image: abroad-stellar-container:latest
          command: ["node"]
          args: ["dist/listeners/index.js"]
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - ps aux | grep '[n]ode dist/listeners/index.js' 
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3 
            failureThreshold: 3


---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: abroad-stellar-sa
