apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - abroad-listeners.yaml
  - abroad-consumers.yaml

images:
  - name: abroad-listeners-container
    newName: us-east1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${REPO_NAME}/${_SERVICE_NAME}
    newTag: ${COMMIT_SHA}
  - name: abroad-consumers-container
    newName: us-east1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${REPO_NAME}/${_SERVICE_NAME}
    newTag: ${COMMIT_SHA}
