const secretEntries = [
  ['BREB_API_BASE_URL', 'BREB_API_BASE_URL'],
  ['BREB_AUTH_URL', 'BREB_AUTH_URL'],
  ['BREB_CLIENT_ID', 'BREB_CLIENT_ID'],
  ['BREB_CLIENT_SECRET', 'BREB_CLIENT_SECRET'],
  ['BREB_DAD_ACCOUNT', 'BREB_DAD_ACCOUNT'],
  ['BREB_PRODUCT_CODE', 'BREB_PRODUCT_CODE'],
  ['ABROAD_WEBHOOK_SECRET', 'ABROAD_WEBHOOK_SECRET'],
  ['ABROAD_WEBHOOK_SECRETS_BY_ORIGIN', 'ABROAD_WEBHOOK_SECRETS_BY_ORIGIN'],
  ['BINANCE_API_KEY', 'BINANCE_API_KEY'],
  ['BINANCE_API_SECRET', 'BINANCE_API_SECRET'],
  ['BINANCE_API_URL', 'BINANCE_API_URL'],
  ['BITSO_API_KEY', 'BITSO_API_KEY'],
  ['CELO_DEPOSIT_ADDRESS', 'CELO_DEPOSIT_ADDRESS'],
  ['CELO_PRIVATE_KEY', 'CELO_PRIVATE_KEY'],
  ['CELO_RPC_URL', 'CELO_RPC_URL'],
  ['DATABASE_URL', 'DATABASE_URL'],
  ['GCP_KEY_FILENAME', 'GCP_KEY_FILENAME'],
  ['GCP_PROJECT_ID', 'GCP_PROJECT_ID'],
  ['GUARDLINE_TENANT_ID', 'GUARDLINE_TENANT_ID'],
  ['PERSONA_API_KEY', 'PERSONA_API_KEY'],
  ['PERSONA_INQUIRY_TEMPLATE_ID', 'PERSONA_INQUIRY_TEMPLATE_ID'],
  ['RABBITMQ_URL', 'RABBITMQ_URL'],
  ['SLACK_WEBHOOK_URL', 'SLACK_WEBHOOK_URL'],
  ['SOLANA_ADDRESS', 'SOLANA_ADDRESS'],
  ['SOLANA_PRIVATE_KEY', 'SOLANA_PRIVATE_KEY'],
  ['SOLANA_RPC_URL', 'SOLANA_RPC_URL'],
  ['STELLAR_ACCOUNT_ID', 'STELLAR_ACCOUNT_ID'],
  ['STELLAR_HOME_DOMAIN', 'STELLAR_HOME_DOMAIN'],
  ['STELLAR_HORIZON_URL', 'STELLAR_HORIZON_URL'],
  ['STELLAR_NETWORK_PASSPHRASE', 'STELLAR_NETWORK_PASSPHRASE'],
  ['STELLAR_PRIVATE_KEY', 'STELLAR_PRIVATE_KEY'],
  ['STELLAR_RECONCILIATION_SECRET', 'STELLAR_RECONCILIATION_SECRET'],
  ['STELLAR_SEP_JWT_SECRET', 'STELLAR_SEP_JWT_SECRET'],
  ['STELLAR_SEP_PARTNER_ID', 'STELLAR_SEP_PARTNER_ID'],
  ['STELLAR_WEB_AUTH_DOMAIN', 'STELLAR_WEB_AUTH_DOMAIN'],
  ['MOVII_BALANCE_ACCOUNT_ID', 'MOVII_BALANCE_ACCOUNT_ID'],
  ['MOVII_BALANCE_API_KEY', 'MOVII_BALANCE_API_KEY'],
  ['OPS_API_KEY', 'OPS_API_KEY'],
  ['PARTNER_PORTAL_DATA_ENCRYPTION_KEY', 'PARTNER_PORTAL_DATA_ENCRYPTION_KEY'],
  ['PARTNER_PORTAL_JWT_SECRET', 'PARTNER_PORTAL_JWT_SECRET'],
  ['TRANSFERO_ULTRA_API_SECRET', 'TRANSFERO_ULTRA_API_SECRET'],
  ['TRANSFERO_ULTRA_BASE_URL', 'TRANSFERO_ULTRA_BASE_URL'],
  ['TRANSFERO_ULTRA_KEY_ID', 'TRANSFERO_ULTRA_KEY_ID'],
  ['TRANSFERO_ULTRA_WEBHOOK_SECRET', 'TRANSFERO_ULTRA_WEBHOOK_SECRET'],
  ['TRANSFERO_ULTRA_WEBHOOK_URL', 'TRANSFERO_ULTRA_WEBHOOK_URL'],
] as const

export interface ISecretManager {
  getSecret(secretName: Secret): Promise<string>
  getSecrets<T extends readonly Secret[]>(
    secretNames: T
  ): Promise<Record<T[number], string>>
}

export type Secret = typeof secretEntries[number][1]
type SecretKey = typeof secretEntries[number][0]

export const Secrets: Record<SecretKey, Secret> = Object.freeze(
  Object.fromEntries(secretEntries) as Record<SecretKey, Secret>,
)
