// src/platform/secrets/ISecretManager.ts
const secretEntries = [
  ['BREB_API_BASE_URL', 'BREB_API_BASE_URL'],
  ['BREB_AUTH_URL', 'BREB_AUTH_URL'],
  ['BREB_CLIENT_ID', 'BREB_CLIENT_ID'],
  ['BREB_CLIENT_SECRET', 'BREB_CLIENT_SECRET'],
  ['BREB_DAD_ACCOUNT', 'BREB_DAD_ACCOUNT'],
  ['BREB_PRODUCT_CODE', 'BREB_PRODUCT_CODE'],
  ['ABROAD_WEBHOOK_SECRET', 'ABROAD_WEBHOOK_SECRET'],
  ['BINANCE_API_KEY', 'BINANCE_API_KEY'],
  ['BINANCE_API_SECRET', 'BINANCE_API_SECRET'],
  ['BINANCE_API_URL', 'BINANCE_API_URL'],
  ['BITSO_API_KEY', 'BITSO_API_KEY'],
  ['DATABASE_URL', 'DATABASE_URL'],
  ['GCP_KEY_FILENAME', 'GCP_KEY_FILENAME'],
  ['GCP_PROJECT_ID', 'GCP_PROJECT_ID'],
  ['GUARDLINE_TENANT_ID', 'GUARDLINE_TENANT_ID'],
  ['MOVII_API_KEY', 'MOVII_API_KEY'],
  ['MOVII_BALANCE_ACCOUNT_ID', 'MOVII_BALANCE_ACCOUNT_ID'],
  ['MOVII_BALANCE_API_KEY', 'MOVII_BALANCE_API_KEY'],
  ['MOVII_BASE_URL', 'MOVII_BASE_URL'],
  ['MOVII_CLIENT_ID', 'MOVII_CLIENT_ID'],
  ['MOVII_CLIENT_SECRET', 'MOVII_CLIENT_SECRET'],
  ['MOVII_QS_ACCOUNT', 'MOVII_QS_ACCOUNT'],
  ['MOVII_QS_LOGIN_URL', 'MOVII_QS_LOGIN_URL'],
  ['MOVII_QS_PASSWORD', 'MOVII_QS_PASSWORD'],
  ['MOVII_QS_USER', 'MOVII_QS_USER'],
  ['MOVII_SIGNER_HANDLER', 'MOVII_SIGNER_HANDLER'],
  ['NEQUI_ACCESS_KEY', 'ACCESS_KEY_NEQUI'],
  ['NEQUI_API_KEY', 'API_KEY_NEQUI'],
  ['NEQUI_DISPERSION_CODE', 'DISPERSION_CODE_NEQUI'],
  ['NEQUI_SECRET_KEY', 'SECRET_KEY_NEQUI'],
  ['NEQUI_URL', 'URL_NEQUI'],
  ['NEQUI_URL_AUTH', 'URL_NEQUI_AUTH'],
  ['PERSONA_API_KEY', 'PERSONA_API_KEY'],
  ['PERSONA_INQUIRY_TEMPLATE_ID', 'PERSONA_INQUIRY_TEMPLATE_ID'],
  ['RABBITMQ_URL', 'RABBITMQ_URL'],
  ['REDIS_URL', 'REDIS_URL'],
  ['SLACK_WEBHOOK_URL', 'SLACK_WEBHOOK_URL'],
  ['SOLANA_ADDRESS', 'SOLANA_ADDRESS'],
  ['SOLANA_PRIVATE_KEY', 'SOLANA_PRIVATE_KEY'],
  ['SOLANA_RPC_URL', 'SOLANA_RPC_URL'],
  ['SOLANA_USDC_MINT', 'SOLANA_USDC_MINT'],
  ['STELLAR_ACCOUNT_ID', 'STELLAR_ACCOUNT_ID'],
  ['STELLAR_HOME_DOMAIN', 'STELLAR_HOME_DOMAIN'],
  ['STELLAR_HORIZON_URL', 'STELLAR_HORIZON_URL'],
  ['STELLAR_NETWORK_PASSPHRASE', 'STELLAR_NETWORK_PASSPHRASE'],
  ['STELLAR_PRIVATE_KEY', 'STELLAR_PRIVATE_KEY'],
  ['STELLAR_SEP_JWT_SECRET', 'STELLAR_SEP_JWT_SECRET'],
  ['STELLAR_SEP_PARTNER_ID', 'STELLAR_SEP_PARTNER_ID'],
  ['STELLAR_USDC_ISSUER', 'STELLAR_USDC_ISSUER'],
  ['STELLAR_WEB_AUTH_DOMAIN', 'STELLAR_WEB_AUTH_DOMAIN'],
  ['TRANSFERO_ACCOUNT_ID', 'TRANSFERO_ACCOUNT_ID'],
  ['TRANSFERO_BASE_URL', 'TRANSFERO_BASE_URL'],
  ['TRANSFERO_CLIENT_ID', 'TRANSFERO_CLIENT_ID'],
  ['TRANSFERO_CLIENT_SCOPE', 'TRANSFERO_CLIENT_SCOPE'],
  ['TRANSFERO_CLIENT_SECRET', 'TRANSFERO_CLIENT_SECRET'],
  ['TRANSFERO_STELLAR_WALLET', 'TRANSFERO_STELLAR_WALLET'],
] as const

export interface ISecretManager {
  getSecret(secretName: Secret): Promise<string>
  getSecrets<T extends readonly Secret[]>(
    secretNames: T
  ): Promise<Record<T[number], string>>
}

export type Secret = typeof secretEntries[number][1]
type SecretKey = typeof secretEntries[number][0]

export const Secrets: Record<SecretKey, Secret> = Object.freeze(
  Object.fromEntries(secretEntries) as Record<SecretKey, Secret>,
)
