// src/interfaces/ISecretManager.ts

export const Secrets = {
  ACCESS_KEY_NEQUI: 'ACCESS_KEY_NEQUI',
  API_KEY_NEQUI: 'API_KEY_NEQUI',
  BITSO_API_KEY: 'BITSO_API_KEY',
  DATABASE_URL: 'DATABASE_URL',
  DISPERSION_CODE_NEQUI: 'DISPERSION_CODE_NEQUI',
  HORIZON_URL: 'horizon-url',
  MOVII_API_KEY: 'MOVII_API_KEY',
  MOVII_BASE_URL: 'MOVII_BASE_URL',
  MOVII_CLIENT_ID: 'MOVII_CLIENT_ID',
  MOVII_CLIENT_SECRET: 'MOVII_CLIENT_SECRET',
  MOVII_SIGNER_HANDLER: 'MOVII_SIGNER_HANDLER',
  PERSONA_API_KEY: 'PERSONA_API_KEY',
  PERSONA_INQUIRY_TEMPLATE_ID: 'PERSONA_INQUIRY_TEMPLATE_ID',
  RABBITMQ_URL: 'RABBITMQ_URL',
  SECRET_KEY_NEQUI: 'SECRET_KEY_NEQUI',
  SLACK_WEBHOOK_URL: 'SLACK_WEBHOOK_URL',
  SOLANA_ADDRESS: 'SOLANA_ADDRESS',
  SOLANA_RPC_URL: 'SOLANA_RPC_URL',
  SOLANA_USDC_MINT: 'SOLANA_USDC_MINT',
  STELLAR_ACCOUNT_ID: 'stellar-account-id',
  URL_NEQUI: 'URL_NEQUI',
  URL_NEQUI_AUTH: 'URL_NEQUI_AUTH',
} as const

export interface ISecretManager {
  getSecret(secretName: Secret): Promise<string>
}

export type Secret = (typeof Secrets)[keyof typeof Secrets]
