// src/types.ts
export const TYPES = {
  BinanceBalanceUpdatedController: Symbol.for('BinanceBalanceUpdatedController'),
  IDatabaseClientProvider: Symbol.for('IDatabaseClientProvider'),
  IExchangeProvider: Symbol.for('IExchangeProvider'),
  IExchangeProviderFactory: Symbol.for('IExchangeProviderFactory'),
  IKycService: Symbol.for('IKycService'),
  ILogger: Symbol.for('ILogger'),
  IPartnerService: Symbol.for('IPartnerService'),
  IPaymentService: Symbol.for('IPaymentService'),
  IPaymentServiceFactory: Symbol.for('IPaymentServiceFactory'),
  IPixQrDecoder: Symbol.for('IPixQrDecoder'),
  IQueueHandler: Symbol.for('IQueueHandler'),
  ISecretManager: Symbol.for('ISecretManager'),
  ISlackNotifier: Symbol.for('ISlackNotifier'),
  IWalletHandlerFactory: Symbol.for('IWalletHandlerFactory'),
  IWebhookNotifier: Symbol.for('IWebhookNotifier'),
  KycUseCase: Symbol.for('KycUseCase'),
  PaymentSentController: Symbol.for('PaymentSentController'),
  PaymentStatusUpdatedController: Symbol.for('PaymentStatusUpdatedController'),
  QuoteUseCase: Symbol.for('QuoteUseCase'),
  ReceivedCryptoTransactionController: Symbol.for('ReceivedCryptoTransactionController'),
  SolanaWalletHandler: Symbol.for('SolanaWalletHandler'),
  StellarWalletHandler: Symbol.for('StellarWalletHandler'),
}
